/**
 * ╔══════════════════════════════════════════════════════════════╗
 * ║              STUDY STORE — PERSISTENT STATE ENGINE            ║
 * ║                                                              ║
 * ║  This is the "single source of truth" for all StudyOS data.  ║
 * ║  Everything persists in localStorage under 'studyos_data_v3'.║
 * ║                                                              ║
 * ║  Key responsibilities:                                       ║
 * ║    1. State types (StudyState, SubjectTask, etc.)           ║
 * ║    2. Forge Protocol: deterministic schedule generation      ║
 * ║    3. Carry-forward: incomplete tasks → debt on new day      ║
 * ║    4. Dashboard stats: completion %, subject breakdown       ║
 * ║    5. Audit logging: every action recorded                   ║
 * ║    6. Neela [ACTION] parsing: AI-generated task creation     ║
 * ║    7. Time utilities: 12h/24h conversion helpers             ║
 * ╚══════════════════════════════════════════════════════════════╝
 */

// ═══════════════════════════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════════════════════════

/** TaskType — Classification for each study task in the scheduler. */
export type TaskType = 'DPP' | 'HOMEWORK' | 'BACKLOG' | 'SURGERY' | 'STUDY';

/** Subject — A subject name string (e.g., "PHYSICS", "CHEMISTRY", "MATHS"). */
export type Subject = string;

/** STANDARD_SUBJECTS — The core PCM subjects for JEE preparation. */
export const STANDARD_SUBJECTS = ['PHYSICS', 'CHEMISTRY', 'MATHS'] as const;

/**
 * SubjectConfig — User-defined subject for schedule generation.
 *   name     → "PHYSICS", "CHEMISTRY", etc.
 *   priority → 1 (low) to 3 (high). Higher priority = more time allocated.
 */
export interface SubjectConfig {
  name: string;
  priority: number;
}

/**
 * TestResult — A single mock test entry logged by the user.
 * Used by TestResultEngine to predict JEE 2027 score.
 */
export interface TestResult {
  id: string;                       // Unique ID
  date: string;                     // "2026-07-24"
  testName: string;                 // e.g., "AITS Phase 1"
  provider: string;                 // "FIITJEE", "ALLEN", etc.
  score: number;                    // Marks obtained
  total: number;                    // Total marks possible
  rank: number;                     // User's rank in the test
  totalStudents: number;            // Total candidates in the test
  overallPercentile: number;        // Mock percentile from rank
  subjectPercentiles: Record<Subject, number>; // Per-subject percentiles
  jeeEquivalentPercentile: number;   // Scaled to JEE 2027 equivalent
  targetPercentile: number;          // Next milestone target
}

/** ChatMessage — A single message in the Neela chat history. */
export interface ChatMessage {
  role: 'user' | 'assistant';       // Who sent the message
  content: string;                  // Markdown-formatted message body
  timestamp: string;                // ISO timestamp
}

/** ChatSession — A full conversation with Neela. Multiple sessions are saved. */
export interface ChatSession {
  id: string;                       // Unique session ID
  timestamp: string;                // Session creation time
  title: string;                    // Session title (first user message)
  messages: ChatMessage[];          // Ordered message history
}

/**
 * SubjectTask — A single study block in the schedule.
 * Generated by the Forge Protocol algorithm.
 */
export interface SubjectTask {
  id: string;                       // Unique task ID
  subject: Subject;                 // e.g., "PHYSICS"
  subjectDisplay?: string;          // Display name (may differ from subject)
  type: TaskType;                   // Task classification
  title: string;                    // e.g., "PHYSICS Focused Study"
  subtitle: string;                 // e.g., "Deep work on PHYSICS"
  duration: number;                 // Duration in minutes
  startTime: string;                // "8:00 PM" (12h format)
  endTime: string;                  // "9:15 PM" (12h format)
  completed: boolean;               // Has the user marked this done?
  date: string;                     // "2026-07-24"
  isDebt: boolean;                  // Carried over from a previous day?
  priority: number;                 // 1-3 priority level
}

/** AuditEntry — A single event in the audit trail. */
export interface AuditEntry {
  timestamp: string;                // ISO timestamp
  action: string;                   // e.g., "START_STUDY", "COMPLETE_TASK"
  reason?: string;                  // Optional description
  metadata?: any;                   // Extra data (task ID, duration, etc.)
}

/** StudySessionState — Current study session runtime state. */
export interface StudySessionState {
  isActive: boolean;                // Is a study timer running?
  isBreak: boolean;                 // Is a break timer running?
  currentTaskId: string | null;     // Which task is being worked on
  currentTaskIndex: number;         // Index in the task list
  studyStartedAt: number | null;    // Date.now() when study started
  breakStartedAt: number | null;    // Date.now() when break started
  totalStudySeconds: number;        // Accumulated study time this session
  totalBreakSeconds: number;        // Accumulated break time this session
  breakCount: number;               // How many breaks taken
  completedTaskIds: string[];       // IDs of completed tasks
}

/**
 * StudyState — THE SINGLE SOURCE OF TRUTH.
 * This entire object is serialized to localStorage.
 */
export interface StudyState {
  tasks: SubjectTask[];             // All study tasks (today + debt)
  auditLog: AuditEntry[];           // Full audit trail (last 100 entries)
  testResults: TestResult[];        // Mock test history (newest first)
  chatHistory: ChatSession[];       // Neela conversation history
  pcm: any;                         // PCM chapter health data (legacy)
  lastLogin: string;                // Date of last login ("2026-07-24")
  session: StudySessionState;       // Current study session state
  config: {                         // User configuration
    startTime: string;              // "18:00" (24h)
    endTime: string;                // "23:00" (24h)
    breakInterval: number;          // Minutes between breaks
    breakDuration: number;          // Break length in minutes
  };
}

// ═══════════════════════════════════════════════════════════════
// TIME UTILITIES
// ═══════════════════════════════════════════════════════════════

/**
 * parseTime12toMinutes(timeStr)
 * Converts 12h time string → minutes from midnight.
 * "8:00 PM"  → 1200 (20 * 60)
 * "01:30 AM" → 90   (1.5 * 60)
 */
export const parseTime12toMinutes = (timeStr: string): number => {
  const match12 = timeStr.match(/(\d{1,2}):(\d{2})\s*(AM|PM)/i);
  if (match12) {
    let hours = parseInt(match12[1]);
    const minutes = parseInt(match12[2]);
    const ampm = match12[3].toUpperCase();
    // Adjust for 12h clock: 12 PM = 12, 12 AM = 0
    if (ampm === 'PM' && hours !== 12) hours += 12;
    if (ampm === 'AM' && hours === 12) hours = 0;
    return hours * 60 + minutes;
  }
  // Fallback: try 24h format ("18:00")
  const [h, m] = timeStr.split(':').map(Number);
  return h * 60 + (m || 0);
};

/**
 * formatMinutesTo12(minutes)
 * Converts minutes from midnight → 12h time string.
 * Example: 1200 → "8:00 PM", 90 → "1:30 AM"
 */
export const formatMinutesTo12 = (minutes: number): string => {
  // Normalize to 0-1439 range (handle cross-midnight values)
  const totalMinutes = ((minutes % 1440) + 1440) % 1440;
  const h = Math.floor(totalMinutes / 60);
  const min = totalMinutes % 60;
  const ampm = h >= 12 ? 'PM' : 'AM';
  const h12 = h % 12 || 12; // Convert 0 → 12 for 12 AM
  return `${h12}:${String(min).padStart(2, '0')} ${ampm}`;
};

/** getCurrentTimeMinutes() — Returns current time as minutes from midnight. */
export const getCurrentTimeMinutes = (): number => {
  const now = new Date();
  return now.getHours() * 60 + now.getMinutes();
};

// ═══════════════════════════════════════════════════════════════
// FORGE PROTOCOL — SCHEDULE GENERATION ALGORITHM
// ═══════════════════════════════════════════════════════════════

/** ScheduleResult — Output of the schedule generation algorithm. */
export interface ScheduleResult {
  tasks: SubjectTask[];                          // Generated study blocks
  totalMinutes: number;                          // Total study time in minutes
  subjectAllocations: {                          // Per-subject breakdown
    subject: string;
    minutes: number;
    percentage: number;
  }[];
}

/**
 * generateDynamicSchedule()
 * ─────────────────────────────────────────────────────────────────
 * THE FORGE PROTOCOL — The core scheduling algorithm.
 *
 * Inputs:
 *   subjects        → Array of {name, priority}
 *   startTimeStr    → "8:00 PM"
 *   endTimeStr      → "1:30 AM"
 *   breakInterval   → Study for X minutes, then break (default: 50)
 *   breakDuration   → Break for Y minutes (default: 10)
 *
 * Algorithm:
 *   1. Calculate totalAvailable minutes (handles cross-midnight)
 *   2. Distribute minutes across subjects proportionally to priority
 *   3. Sort subjects by priority (high priority first)
 *   4. Round-robin: allocate blocks for each subject until time runs out
 *   5. Insert breaks every breakInterval minutes
 *   6. Skip subjects that have received their full allocation
 *   7. Safety: maxIterations prevents infinite loops
 *
 * Priority weighting:
 *   totalWeight = sum of all subject priorities
 *   subjectAllocation = (subject.priority / totalWeight) * totalAvailable
 *   P3 subjects get ~50% more time than P2, ~3x more than P1
 */
export const generateDynamicSchedule = (
  subjects: SubjectConfig[],
  startTimeStr: string,
  endTimeStr: string,
  breakInterval: number = 50,    // Study for 50 min before break
  breakDuration: number = 10      // Break for 10 min
): ScheduleResult => {
  let currentMinutes = parseTime12toMinutes(startTimeStr);    // Start in minutes
  let endMinutes = parseTime12toMinutes(endTimeStr);          // End in minutes

  // Handle cross-midnight study sessions (e.g., 8:00 PM → 1:30 AM)
  if (endMinutes <= currentMinutes) {
    endMinutes += 24 * 60; // Add 24 hours to end time
  }

  const totalAvailable = endMinutes - currentMinutes;          // Total study window

  // Guard: no time available or no subjects configured
  if (totalAvailable <= 0 || subjects.length === 0) {
    return { tasks: [], totalMinutes: 0, subjectAllocations: [] };
  }

  const tasks: SubjectTask[] = [];
  const totalWeight = subjects.reduce((acc, s) => acc + s.priority, 0);

  // Sort by priority descending (P3 first, then P2, then P1)
  const sortedSubjects = [...subjects].sort((a, b) => b.priority - a.priority);

  // Calculate proportional allocations
  const allocations: { name: string; priority: number; allocated: number }[] =
    sortedSubjects.map(s => ({
      name: s.name,
      priority: s.priority,
      allocated: (s.priority / totalWeight) * totalAvailable
    }));

  // Build the allocation summary for the preview UI
  const subjectAllocations = allocations.map(a => ({
    subject: a.name,
    minutes: Math.round(a.allocated),
    percentage: Math.round((a.allocated / totalAvailable) * 100)
  }));

  let timeSinceLastBreak = 0;          // Minutes since last break insertion
  const today = new Date().toISOString().split('T')[0]; // "2026-07-24"
  let subjectIndex = 0;                // Current subject being allocated
  const maxIterations = 1000;          // Safety: prevent infinite loops
  let iterations = 0;

  // Main allocation loop
  while (currentMinutes < endMinutes && subjectIndex < sortedSubjects.length && iterations < maxIterations) {
    iterations++;

    // ── BREAK CHECK ────────────────────────────────────────────
    // If we've studied for breakInterval minutes, insert a break
    if (timeSinceLastBreak >= breakInterval) {
      const breakEnd = Math.min(currentMinutes + breakDuration, endMinutes);
      currentMinutes = breakEnd;        // Skip ahead past the break
      timeSinceLastBreak = 0;          // Reset break counter
      continue;                         // Re-evaluate from the top
    }

    const sub = allocations[subjectIndex];
    if (!sub) break; // Safety: shouldn't happen

    // How many minutes have we already allocated to this subject?
    const alreadyAllocated = tasks
      .filter(t => t.subject === sub.name)
      .reduce((acc, t) => acc + t.duration, 0);

    const remainingForSubject = sub.allocated - alreadyAllocated;

    // If this subject has received its full allocation, move to the next
    if (remainingForSubject <= 0) {
      subjectIndex++;
      continue;
    }

    // Calculate the actual block duration:
    //   Min of: remaining for subject, remaining total time, time until next break
    const remainingTime = endMinutes - currentMinutes;
    const availableBeforeBreak = breakInterval - timeSinceLastBreak;
    const duration = Math.min(remainingForSubject, remainingTime, availableBeforeBreak);

    // Skip blocks smaller than 10 minutes (too short to be meaningful)
    if (duration < 10) {
      subjectIndex++;
      continue;
    }

    // Commit the block
    const blockStartMinutes = currentMinutes;
    currentMinutes += duration;
    timeSinceLastBreak += duration;

    tasks.push({
      id: Math.random().toString(36).substr(2, 9),    // Random alphanumeric ID
      subject: sub.name,
      subjectDisplay: sub.name,
      type: 'STUDY',
      title: `${sub.name} Focused Study`,
      subtitle: `Deep work on ${sub.name}`,
      duration: Math.floor(duration),
      startTime: formatMinutesTo12(blockStartMinutes),
      endTime: formatMinutesTo12(currentMinutes),
      completed: false,
      date: today,
      isDebt: false,
      priority: sub.priority
    });
  }

  return { tasks, totalMinutes: totalAvailable, subjectAllocations };
};

// ═══════════════════════════════════════════════════════════════
// REBALANCE AFTER BREAK
// ═══════════════════════════════════════════════════════════════

/**
 * rebalanceSchedule()
 * Recalculates the remaining schedule after a break or task completion.
 * Takes remaining incomplete tasks and regenerates from current time.
 */
export const rebalanceSchedule = (
  currentTasks: SubjectTask[],
  completedTaskIds: string[],
  currentTimeStr: string,
  endTimeStr: string,
  breakInterval: number = 50,
  breakDuration: number = 10
): ScheduleResult => {
  // Filter out completed tasks
  const remainingTasks = currentTasks.filter(t => !completedTaskIds.includes(t.id));

  // Extract unique subjects with their priorities from remaining tasks
  const subjectPriorityMap = new Map<string, number>();
  remainingTasks.forEach(t => {
    const existing = subjectPriorityMap.get(t.subject);
    if (!existing || t.priority > existing) {
      subjectPriorityMap.set(t.subject, t.priority);
    }
  });

  // Check if endTime has already passed
  const currentMinutes = parseTime12toMinutes(currentTimeStr);
  let endMinutes = parseTime12toMinutes(endTimeStr);
  if (endMinutes <= currentMinutes) {
    endMinutes += 24 * 60;
  }

  // Nothing left to schedule
  if (currentMinutes >= endMinutes || subjectPriorityMap.size === 0) {
    return { tasks: [], totalMinutes: 0, subjectAllocations: [] };
  }

  const subjects: SubjectConfig[] = Array.from(subjectPriorityMap.entries()).map(
    ([name, priority]) => ({ name, priority })
  );

  // Regenerate from current time with remaining subjects
  return generateDynamicSchedule(subjects, currentTimeStr, endTimeStr, breakInterval, breakDuration);
};

// ═══════════════════════════════════════════════════════════════
// DASHBOARD STATISTICS
// ═══════════════════════════════════════════════════════════════

/** DashboardStats — Computed analytics for the scheduler dashboard. */
export interface DashboardStats {
  totalTasks: number;
  completedTasks: number;
  completionRate: number;             // 0-100 percentage
  totalStudyMinutes: number;
  totalBreakMinutes: number;
  breakCount: number;
  subjectBreakdown: {                 // Per-subject analytics
    subject: string;
    totalMinutes: number;
    completedMinutes: number;
    tasksCount: number;
    completedTasks: number;
  }[];
  todayAuditLog: AuditEntry[];        // Today's audit trail entries
}

/**
 * calculateDashboardStats(tasks, auditLog)
 * Computes today's study statistics from tasks and audit trail.
 * Used by the Scheduler's dashboard panel.
 */
export const calculateDashboardStats = (
  tasks: SubjectTask[],
  auditLog: AuditEntry[]
): DashboardStats => {
  const today = new Date().toISOString().split('T')[0];
  const todayTasks = tasks.filter(t => t.date === today);
  const todayAuditLog = auditLog.filter(e => e.timestamp.startsWith(today));

  const totalTasks = todayTasks.length;
  const completedTasks = todayTasks.filter(t => t.completed).length;
  const completionRate = totalTasks > 0
    ? Math.round((completedTasks / totalTasks) * 100)
    : 0;

  const totalStudyMinutes = todayTasks.reduce((acc, t) => acc + t.duration, 0);

  // Extract break stats from audit log
  const breakStarts = todayAuditLog.filter(e => e.action === 'START_BREAK');
  const breakEnds = todayAuditLog.filter(e => e.action === 'STOP_BREAK');
  const breakCount = breakStarts.length;

  let totalBreakMinutes = 0;
  breakEnds.forEach(e => {
    if (e.metadata?.durationSeconds) {
      totalBreakMinutes += Math.ceil(e.metadata.durationSeconds / 60);
    }
  });

  // Per-subject breakdown
  const subjectMap = new Map<string, {
    totalMin: number;
    completedMin: number;
    tasksCount: number;
    completedTasks: number;
  }>();

  todayTasks.forEach(t => {
    const key = t.subjectDisplay || t.subject;
    const existing = subjectMap.get(key) || {
      totalMin: 0, completedMin: 0, tasksCount: 0, completedTasks: 0
    };
    existing.totalMin += t.duration;
    existing.tasksCount += 1;
    if (t.completed) {
      existing.completedMin += t.duration;
      existing.completedTasks += 1;
    }
    subjectMap.set(key, existing);
  });

  const subjectBreakdown = Array.from(subjectMap.entries()).map(([subject, data]) => ({
    subject,
    totalMinutes: data.totalMin,
    completedMinutes: data.completedMin,
    tasksCount: data.tasksCount,
    completedTasks: data.completedTasks
  }));

  return {
    totalTasks,
    completedTasks,
    completionRate,
    totalStudyMinutes,
    totalBreakMinutes,
    breakCount,
    subjectBreakdown,
    todayAuditLog
  };
};

// ═══════════════════════════════════════════════════════════════
// PERSISTENCE (localStorage)
// ═══════════════════════════════════════════════════════════════

const STORAGE_KEY = 'studyos_data_v3';   // localStorage key

/** createDefaultState() — Returns a fresh StudyState with sensible defaults. */
const createDefaultState = (): StudyState => ({
  tasks: [],
  auditLog: [],
  testResults: [],
  chatHistory: [],
  pcm: {
    physics:   [{ name: 'Rotation',        dpps: [], backlogs: [] }],
    chemistry: [{ name: 'Thermodynamics',   dpps: [], backlogs: [] }],
    maths:     [{ name: 'Integration',      dpps: [], backlogs: [] }],
  },
  lastLogin: new Date().toISOString().split('T')[0],
  session: {
    isActive: false, isBreak: false,
    currentTaskId: null, currentTaskIndex: -1,
    studyStartedAt: null, breakStartedAt: null,
    totalStudySeconds: 0, totalBreakSeconds: 0,
    breakCount: 0, completedTaskIds: []
  },
  config: {
    startTime: "18:00", endTime: "23:00",
    breakInterval: 50, breakDuration: 10
  }
});

/** loadState() — Reads StudyState from localStorage, or returns a fresh default. */
export const loadState = (): StudyState => {
  const saved = localStorage.getItem(STORAGE_KEY);
  try {
    if (saved) {
      const parsed = JSON.parse(saved);
      // Migrate: ensure session field exists for legacy data
      if (!parsed.session) {
        parsed.session = createDefaultState().session;
      }
      return parsed as StudyState;
    }
  } catch (e) {
    // Corrupted data → start fresh (graceful degradation)
  }
  return createDefaultState();
};

/** saveState(state) — Persists the entire StudyState to localStorage. */
export const saveState = (state: StudyState) => {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
  } catch (e) {
    console.error('[StudyOS] Failed to save state:', e);
  }
};

// ═══════════════════════════════════════════════════════════════
// STATE HELPERS
// ═══════════════════════════════════════════════════════════════

/**
 * updateChatSession(state, session)
 * Upserts a chat session into the chatHistory array.
 * If the session already exists (by ID), updates it.
 * If new, prepends it (newest first).
 * Auto-saves to localStorage.
 */
export const updateChatSession = (state: StudyState, session: ChatSession): StudyState => {
  const existingIdx = state.chatHistory.findIndex(s => s.id === session.id);
  let newHistory = [...state.chatHistory];
  if (existingIdx >= 0) {
    newHistory[existingIdx] = session;  // Update existing
  } else {
    newHistory = [session, ...newHistory]; // Prepend new
  }
  const newState = { ...state, chatHistory: newHistory };
  saveState(newState);
  return newState;
};

/**
 * calculateCarryForward(tasks)
 * Converts incomplete past tasks into "debt" tasks.
 * Called once per day on app mount (when lastLogin !== today).
 * Tasks with isDebt: true appear with high priority in the scheduler.
 */
export const calculateCarryForward = (tasks: SubjectTask[]): SubjectTask[] => {
  const today = new Date().toISOString().split('T')[0];
  return tasks.map(task => {
    if (!task.completed && task.date < today && !task.isDebt) {
      return { ...task, isDebt: true };
    }
    return task;
  });
};

/**
 * logAction(state, action, reason?, metadata?)
 * Appends an audit entry to the audit log.
 * Keeps only the last 100 entries (prevents unbounded growth).
 * Auto-saves to localStorage.
 */
export const logAction = (
  state: StudyState,
  action: string,
  reason?: string,
  metadata?: any
): StudyState => {
  const entry: AuditEntry = {
    timestamp: new Date().toISOString(),
    action,
    reason,
    metadata
  };
  // Keep only the last 100 entries + the new one
  const newState = {
    ...state,
    auditLog: [...state.auditLog.slice(-99), entry]
  };
  saveState(newState);
  return newState;
};

// ═══════════════════════════════════════════════════════════════
// NEELA [ACTION] PROCESSING
// ═══════════════════════════════════════════════════════════════

/**
 * processNeelaAction(state, aiResponse)
 * Parses [ACTION]...[\/ACTION] blocks from Neela's AI response.
 * Neela can issue structured commands that modify the app state:
 *
 *   ADD_TASKS: Create new study tasks in the scheduler
 *     Example: { "type": "ADD_TASKS", "payload": [{ "subject": "PHYSICS", ... }] }
 *
 *   UPDATE_PCM: Update PCM chapter health data
 *     Example: { "type": "UPDATE_PCM", "payload": { "subject": "PHYSICS", ... } }
 *
 * This is the core of Neela's "agentic" capability — she's not just
 * a chatbot, she can directly modify the user's study plan.
 */
export const processNeelaAction = (state: StudyState, aiResponse: string): StudyState => {
  try {
    // Extract [ACTION] block from the AI response
    const actionMatch = aiResponse.match(/\[ACTION\]([\s\S]*?)\[\/ACTION\]/);
    if (!actionMatch) return state; // No action block found

    const action = JSON.parse(actionMatch[1]); // Parse the JSON payload
    let newState = { ...state };

    // ── ADD_TASKS: Create new study blocks ──────────────────
    if (action.type === 'ADD_TASKS') {
      const today = new Date().toISOString().split('T')[0];
      const newTasks = action.payload.map((t: any) => ({
        id: Math.random().toString(36).substr(2, 9),
        completed: false,
        isDebt: false,
        date: today,
        ...t  // Spread the rest (subject, type, title, duration, startTime, endTime)
      }));
      newState.tasks = [...newState.tasks, ...newTasks];
      newState = logAction(newState, 'NEELA_ADD_TASKS', 'AI generated schedule update');
    }

    // ── UPDATE_PCM: Update chapter health ───────────────────
    if (action.type === 'UPDATE_PCM') {
      const { subject, chapter, dpp, backlog } = action.payload;
      const sub = subject.toLowerCase();
      const chapterIdx = newState.pcm[sub]?.findIndex(
        (c: any) => c.name.toLowerCase() === chapter.toLowerCase()
      );
      if (chapterIdx !== undefined && chapterIdx > -1) {
        if (dpp) newState.pcm[sub][chapterIdx].dpps.push(dpp);
        if (backlog) newState.pcm[sub][chapterIdx].backlogs.push(backlog);
      }
    }

    return newState;
  } catch (e) {
    // If parsing fails, return state unchanged (graceful degradation)
    return state;
  }
};
